name: wa_bot
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  google_generative_ai: 0.2.2
  hidable: 1.0.6
  flutter_markdown: 0.6.21
  cached_network_image: 3.3.1
  rename: 3.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

